export const TRANSACTION_LIST_DEFAULT_PAGE = 1;
export const TRANSACTION_LIST_DEFAULT_LIMIT = 20;
export const TRANSACTION_LIST_MAX_LIMIT = 100;
export const TRANSACTION_LIST_SORT_DATE_DESC = 'date:desc';
export const TRANSACTION_LIST_SORT_DATE_ASC = 'date:asc';
export const TRANSACTION_LIST_DEFAULT_SORT = TRANSACTION_LIST_SORT_DATE_DESC;
export const TRANSACTION_LIST_SORT_VALUES = [TRANSACTION_LIST_SORT_DATE_DESC, TRANSACTION_LIST_SORT_DATE_ASC] as const;
export const TRANSACTION_DESCRIPTION_MAX_LENGTH = 500;
export const TRANSACTION_AMOUNT_CENTS_MAX = Number.MAX_SAFE_INTEGER;

export type TransactionListSort = (typeof TRANSACTION_LIST_SORT_VALUES)[number];
