export const TRANSACTION_LIST_DEFAULT_PAGE = 1;
export const TRANSACTION_LIST_DEFAULT_LIMIT = 20;
export const TRANSACTION_LIST_MAX_LIMIT = 100;
export const TRANSACTION_DESCRIPTION_MAX_LENGTH = 500;
export const TRANSACTION_AMOUNT_CENTS_MAX = Number.MAX_SAFE_INTEGER;
